### ISSUE TITLE
Unclear warning about merging PR before milestone date

### ISSUE THREAD

**Issue by crazytonyli** [Automattic/dangermattic#29]
> This PR is assigned to a milestone which is closing in less than 4 days Please, make sure to get it merged by then or assign it to a later expiring milestone

This warning was added to a PR whose base branch is code-frozen release branch, which is obviously already past the milestone date. The "make sure to get it merged by then" part seems a bit unclear, if "then" means the milestone code freeze date.

See https://github.com/wordpress-mobile/WordPress-iOS/pull/22041#issuecomment-1811527388.

**Comment by iangmaia** [comment]
Thanks for reporting it @crazytonyli, I remember also seeing this scenario somewhere else 👍

**Comment by iangmaia** [comment]
Fixed in #40
